# .github/labeler.yml

labels:
  - name: WIP
    color: #BBCD64 # You can specify the color in hexadecimal format
    description: A work in progress task

  - name: Enhancement
    color: #a2eeef
    description: New feature or request
# You can add more labels as needed
