name: Pull Request Routines

on:
  pull_request:
    types:
      - opened

jobs:
  # label:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set default labels
  #       uses: actions/github-script@v4
  #       with:
  #         script: |
  #           const labelsToAdd = ["WIP", "Enhancement"];  // Add your default labels here
  #           const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

  #           for (const label of labelsToAdd) {
  #             await octokit.rest.issues.addLabels({
  #               owner: context.repo.owner,
  #               repo: context.repo.repo,
  #               issue_number: context.payload.pull_request.number,
  #               labels: [label],
  #             });
  #           }

  link-to-board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Link PR to Project Board
        uses: actions/github-script@v4
        with:
          script: |
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const projectId = '3';  // This is the Task board project ID
            const columnName = 'In progress';  // Let's put it in the column 'In progress'

            // Get the project
            const project = await octokit.rest.projects.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              project_id: projectId,
            });

            // Get the column ID
            const column = project.data.columns.find(c => c.name === columnName);
            const columnId = column ? column.id : null;

            // Add the pull request to the project board column
            if (columnId) {
              await octokit.rest.projects.createCard({
                column_id: columnId,
                content_id: context.payload.pull_request.id,
                content_type: 'PullRequest',
              });
            } else {
              console.log('Column ID not found. Unable to link pull request to the project board.');
            }

  mark-as-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Mark Pull Request as Draft
        run: |
          gh pr edit ${{ github.event.number }} --draft
